skip_tests = {
    "always": [
        "test_reference_numerics_extremal__refs_special_spherical_bessel_j0_cuda_float32",
        "test_reference_numerics_extremal__refs_special_spherical_bessel_j0_cuda_float64",
        "test_reference_numerics_extremal_special_airy_ai_cuda_float32",
        "test_reference_numerics_extremal_special_airy_ai_cuda_float64",
        "test_reference_numerics_extremal_special_spherical_bessel_j0_cuda_float32",
        "test_reference_numerics_extremal_special_spherical_bessel_j0_cuda_float64",
        "test_reference_numerics_large__refs_special_spherical_bessel_j0_cuda_float32",
        "test_reference_numerics_large__refs_special_spherical_bessel_j0_cuda_float64",
        "test_reference_numerics_large__refs_special_spherical_bessel_j0_cuda_int16",
        "test_reference_numerics_large__refs_special_spherical_bessel_j0_cuda_int32",
        "test_reference_numerics_large__refs_special_spherical_bessel_j0_cuda_int64",
        "test_reference_numerics_large_special_spherical_bessel_j0_cuda_float32",
        "test_reference_numerics_large_special_spherical_bessel_j0_cuda_float64",
        "test_reference_numerics_large_special_spherical_bessel_j0_cuda_int16",
        "test_reference_numerics_large_special_spherical_bessel_j0_cuda_int32",
        "test_reference_numerics_large_special_spherical_bessel_j0_cuda_int64",
        "test_reference_numerics_normal__refs_special_spherical_bessel_j0_cuda_bool",
        "test_reference_numerics_normal__refs_special_spherical_bessel_j0_cuda_float32",
        "test_reference_numerics_normal__refs_special_spherical_bessel_j0_cuda_float64",
        "test_reference_numerics_normal__refs_special_spherical_bessel_j0_cuda_int16",
        "test_reference_numerics_normal__refs_special_spherical_bessel_j0_cuda_int32",
        "test_reference_numerics_normal__refs_special_spherical_bessel_j0_cuda_int64",
        "test_reference_numerics_normal__refs_special_spherical_bessel_j0_cuda_int8",
        "test_reference_numerics_normal__refs_special_spherical_bessel_j0_cuda_uint8",
        "test_reference_numerics_normal_special_airy_ai_cuda_bool",
        "test_reference_numerics_normal_special_airy_ai_cuda_float32",
        "test_reference_numerics_normal_special_airy_ai_cuda_float64",
        "test_reference_numerics_normal_special_airy_ai_cuda_int16",
        "test_reference_numerics_normal_special_airy_ai_cuda_int32",
        "test_reference_numerics_normal_special_airy_ai_cuda_int64",
        "test_reference_numerics_normal_special_airy_ai_cuda_int8",
        "test_reference_numerics_normal_special_airy_ai_cuda_uint8",
        "test_reference_numerics_normal_special_spherical_bessel_j0_cuda_bool",
        "test_reference_numerics_normal_special_spherical_bessel_j0_cuda_float32",
        "test_reference_numerics_normal_special_spherical_bessel_j0_cuda_float64",
        "test_reference_numerics_normal_special_spherical_bessel_j0_cuda_int16",
        "test_reference_numerics_normal_special_spherical_bessel_j0_cuda_int32",
        "test_reference_numerics_normal_special_spherical_bessel_j0_cuda_int64",
        "test_reference_numerics_normal_special_spherical_bessel_j0_cuda_int8",
        "test_reference_numerics_normal_special_spherical_bessel_j0_cuda_uint8",
        "test_reference_numerics_small__refs_special_spherical_bessel_j0_cuda_float32",
        "test_reference_numerics_small__refs_special_spherical_bessel_j0_cuda_float64",
        "test_reference_numerics_small__refs_special_spherical_bessel_j0_cuda_int16",
        "test_reference_numerics_small__refs_special_spherical_bessel_j0_cuda_int32",
        "test_reference_numerics_small__refs_special_spherical_bessel_j0_cuda_int64",
        "test_reference_numerics_small__refs_special_spherical_bessel_j0_cuda_int8",
        "test_reference_numerics_small__refs_special_spherical_bessel_j0_cuda_uint8",
        "test_reference_numerics_small_special_airy_ai_cuda_float32",
        "test_reference_numerics_small_special_airy_ai_cuda_float64",
        "test_reference_numerics_small_special_airy_ai_cuda_int16",
        "test_reference_numerics_small_special_airy_ai_cuda_int32",
        "test_reference_numerics_small_special_airy_ai_cuda_int64",
        "test_reference_numerics_small_special_airy_ai_cuda_int8",
        "test_reference_numerics_small_special_airy_ai_cuda_uint8",
        "test_reference_numerics_small_special_spherical_bessel_j0_cuda_float32",
        "test_reference_numerics_small_special_spherical_bessel_j0_cuda_float64",
        "test_reference_numerics_small_special_spherical_bessel_j0_cuda_int16",
        "test_reference_numerics_small_special_spherical_bessel_j0_cuda_int32",
        "test_reference_numerics_small_special_spherical_bessel_j0_cuda_int64",
        "test_reference_numerics_small_special_spherical_bessel_j0_cuda_int8",
        "test_reference_numerics_small_special_spherical_bessel_j0_cuda_uint8",
    ],
    "pytorch_version": {},
    "amdgpu_family": {},
}
# this passed on gfx942
# "test_reference_numerics_large__refs_nn_functional_mish_cuda_float16",
# "test_reference_numerics_large_nn_functional_mish_cuda_float16",
