# clr
[components.dbg."core/clr/stage"]
[components.dev."core/clr/stage"]
[components.doc."core/clr/stage"]
[components.lib."core/clr/stage"]
include = [
  "lib/.hipInfo",
  "share/hip/**",
]
[components.run."core/clr/stage"]
include = [
  "bin/**",
]

# hip-tests
[components.doc."core/hip-tests/stage"]
optional = true
[components.test."core/hip-tests/stage"]
include = [
  "share/hip/**",
]
optional = true
